// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Voting$Type } from "./Voting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Voting"]: Voting$Type;
    ["contracts/Voting.sol:Voting"]: Voting$Type;
  }

  interface ContractTypesMap {
    ["Voting"]: GetContractReturnType<Voting$Type["abi"]>;
    ["contracts/Voting.sol:Voting"]: GetContractReturnType<Voting$Type["abi"]>;
  }
}
